snakefile: "../Snakefile"
local-cores: 1
cores: 256
printshellcmds: true
rerun-incomplete: true
use-conda: true
conda-frontend: mamba
keep-going: true
jobscript: "slurm-jobscript.sh"
cluster: "slurm-submit.py"
cluster-status: "slurm-status.py"
latency-wait: 120
jobs: 256
